# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run: npm ci
      - run: npm run setup:external
      - run: npm run test:platforms
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
