name: Build WASM/ASM.js libraries

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select a library"
        required: true
        default: "Spine"
        type: choice
        options:
          - Spine

jobs:
  build_spine_wasm_asmjs:
    name: "Build spine wasm/asmjs libs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.41

      - name: Verify
        run: |
          which emcc
          emcc -v

      - name: Install ninja
        run: |
          if ! command -v ninja &> /dev/null; then
              echo "Ninja not found, installing..."
              # sudo apt update
              sudo apt install ninja-build
          else
              echo "Ninja is already installed."
          fi
          which ninja

      - name: Build Spine WASM and ASMJS
        run: bash .github/workflows/build-spine.sh dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: spine-emscripten
          path: dist
