name: <Web> npm test

on: [push, pull_request]

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  npm_test:
    if: 
      (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.41

    - name: Verify
      run: |
        which emcc
        emcc -v

    - name: Install ninja
      run: |
        if ! command -v ninja &> /dev/null; then
            echo "Ninja not found, installing..."
            # sudo apt update
            sudo apt install ninja-build
        else
            echo "Ninja is already installed."
        fi
        which ninja
        
    - name: Download external
      run: |
        node .github/workflows/get-external-version.js
        npm run setup:external

    - name: Build Spine WASM and ASMJS
      run: bash .github/workflows/build-spine.sh dist

    - name: Copy Spine files to external directory
      run: |
        for version in 3.8 4.2; do
          mkdir -p "external/emscripten/spine/$version"
          cp "dist/$version/"* "external/emscripten/spine/$version/"
        done

    - name: npm install
      run: |
        npm install
       
    - name: build-debug-infos
      run: |
        npm run build:debug-infos
        
    - name: run test
      run: |
        export NODE_OPTIONS="--max-old-space-size=8192"
        npm test
